version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
  init_queues:
    build: .
    command: ["python3", "init_queues.py"]
    depends_on:
      - localstack
    links:
      - localstack
